### ISSUE TITLE
Background image of the website is not related

### ISSUE THREAD

**Issue by DeepNinja07x** [DeepNinja07x/Weather-JS#1]
Sometimes, based on the city, the background image shown is not related with the city. The image is requested from Unsplash API.

**Comment by DeepNinja07x** [comment]
sure

**Comment by DeepNinja07x** [comment]
start from tomorrow

**Comment by tnmyk** [comment]
I think there is no other option than change the api from unsplash to some other... I have tried making the query name to lowercase which is improving the images but still some of them are not related

**Comment by DeepNinja07x** [comment]
It's better than noting. You can also try it by changing the API. If it works perfectly, I'll merge it; otherwise just change the query name as you've mentioned. I'll merge that too

**Comment by lara-sahoo** [comment]
Hi @DeepNinja07x I looked after this issue and found 3 things:-

1. Using Google Places API. Article on it: - [https://codeburst.io/adding-city-images-to-your-react-app-14c937df2db2](https://codeburst.io/adding-city-images-to-your-react-app-14c937df2db2)
2. Using Teleport API. [http://developers.teleport.org/api/getting_started/](http://developers.teleport.org/api/getting_started/)
3. Using unsplash API [https://unsplash.com/developers](https://unsplash.com/developers)

Have a look at this and let me know which one would you prefer. I would like to work on this.

**Comment by jblancoh** [comment]
I made you a PR with the google place API
