### ISSUE TITLE
API Key is Invalid.

### ISSUE THREAD

**Issue by karanchoudhxry** [DeepNinja07x/Weather-JS#14]
**Description**
Hi, the app is not able to fetch data from the API and the server is responding with an Error Code: 401. That is because the API key is invalid.

**Screenshots**
![Screenshot 2021-10-16 134141](https://user-images.githubusercontent.com/66913745/137580084-8e9a4da4-8c0a-4c8c-bb3c-4b09b82da05b.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 94

**Additional context**
To fix this error change or update your API Key.

Thank You 🙏

**Comment by DeepNinja07x** [comment]
It is because I've deleted the API Key.......Just create one and then use it. Since it's an open source, any API Key can't be made visible for security purposes
